INPUTS:
  - token: "value"
    customStatus: true  # / false 
    voiceEnabled: true  # / false
    activity:
      type: "LISTENING" # STREAMING, PLAYING, LISTENING, WATCHING, COMPETING

OPTIONS:
  location: "Bangkok" # default
  tz: "Asia/Bangkok" # default

VOICE:
  autoRejoinDelay: 5000 # default
  data: "sx!" # Command prefix | Examples: sx!join <vcid>, sx!leave


  # require ffmpeg
  ffmpeg: false # Default 

  commands_example : |
    sx!j  = join
    sx!l  = leave
    sx!pl = play-live ( sx!pl <vcid> <url> )
    sx!s  = stop-stream
    sx!ls = list ( in console )


  width: 1280          #  (default: 1280)
  height: 720          #  (default: 720)
  fps: 30              #  (default: 30)
  bitrateKbps: 1000    #  (default: 1000)
  maxBitrateKbps: 2500 #  (default: 2500)
  hardware_acceleration: false #  (default: false)
  videoCodec: "H264"   # Video codec: H264, H265, VP8, VP9 (default: H264)

STATUS:
  delay: 4000 # default (Minimum 4000)
  data:
    - emoji: "ðŸ§¡"
      text: "TEXT 1"
    - emoji: "ðŸ’›"
      text: "TEXT 2"
    - emoji: "ðŸ’š"
      text: "TEXT 3"
    - emoji: "ðŸ’™"
      text: "TEXT 4"
    - emoji: "ðŸ’œ"
      text: "TEXT 5"

RPC:
  delay: 4000 # default (Minimum 4000)

  # this for type listening only | comment to disable place "#" in the front start and end like #start ... #end
  timestamp:
      start: "2025-09-02T07:45:34.593Z" # ISO8601 | timestamp in milliseconds
      end: "2029-12-31T17:00:00.000Z" # ISO8601 | timestamp in milliseconds

  # uncomment to enable switch both Youtube type, Twitch type activity 
  TwitchURL: "https://www.twitch.tv/4levy_z1"
  #YoutubeURL: "https://www.youtube.com/@4levy"

  details:
    - "Details"
  state:
    - "State"
  assetsLargeText:
    - "AssetsLargeText"
  assetsSmallText:
    - "AssetsSmallText"
  assetsLargeImage:
    - "https://i.postimg.cc/DzRFzTV6/angel_angelcore_aesthetic_fantasy_creatures_fantasy.jpg"
  assetsSmallImage:
    - "https://i.pinimg.com/1200x/e6/b4/a7/e6b4a73f43ab3fdaed7c6af5b814dedd.jpg"
  buttonFirst:
    - label: "> Server <"
      url: "https://server.0nyx.wtf/"
  buttonSecond:
    - label: "[ Server ]"
      url: "https://discord.gg/pQVtDP8GEE"